[package]
name = "atmega-usbd"
version = "0.1.0"
edition = "2021"

[dependencies]
avr-device = { version = "0.3", features = ["atmega32u4"] }
usb-device = "0.2"

[profile.dev]
opt-level = "s"
lto = true

[profile.release]
opt-level = "s"
lto = true